name: Snowflake CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    env:
        SNOWSQL_PWD: ${{ secrets.SNOWSQL_PASSWORD }}
        SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
        SNOWSQL_USERNAME: ${{ secrets.SNOWSQL_USERNAME }}
        SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
        SNOWSQL_SCHEMA: ${{ secrets.SNOWSQL_SCHEMA }}
        SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SnowSQL
        run: |
          curl -o snowsql-linux_x86_64.bash https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.27-linux_x86_64.bash
          chmod +x snowsql-linux_x86_64.bash
          echo -ne '\n\n' | bash snowsql-linux_x86_64.bash
          ~/bin/snowsql -v

      - name: Create Snowflake warehouse
        env:
            SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
            SNOWSQL_USERNAME: ${{ secrets.SNOWSQL_USERNAME }}
            SNOWSQL_PASSWORD: ${{ secrets.SNOWSQL_PASSWORD }}
        run: |
          ~/bin/snowsql -a ${{ secrets.SNOWSQL_ACCOUNT }} -u ${{ secrets.SNOWSQL_USERNAME }} -w ${{ secrets.SNOWSQL_WAREHOUSE }} -d ${{ secrets.SNOWSQL_DATABASE }} -s ${{ secrets.SNOWSQL_SCHEMA }} -f create_warehouse.sql
  

      - name: Run tests
        run: |
          ~/bin/snowsql -a ${{ secrets.SNOWSQL_ACCOUNT }} -u ${{ secrets.SNOWSQL_USERNAME }} -w ${{ secrets.SNOWSQL_WAREHOUSE }} -d ${{ secrets.SNOWSQL_DATABASE }} -s ${{ secrets.SNOWSQL_SCHEMA }} -f create_table.sql
          ~/bin/snowsql -a ${{ secrets.SNOWSQL_ACCOUNT }} -u ${{ secrets.SNOWSQL_USERNAME }} -w ${{ secrets.SNOWSQL_WAREHOUSE }} -d ${{ secrets.SNOWSQL_DATABASE }} -s ${{ secrets.SNOWSQL_SCHEMA }} -f test_table.sql

      - name: Deploy to Snowflake
        run: |
         ~/bin/snowsql -a ${{ secrets.SNOWSQL_ACCOUNT }} -u ${{ secrets.SNOWSQL_USERNAME }} -w ${{ secrets.SNOWSQL_WAREHOUSE }} -d ${{ secrets.SNOWSQL_DATABASE }} -s ${{ secrets.SNOWSQL_SCHEMA }} -f create_table.sql
